// OTU 产品数据 - 从 PPTX 提取
const products = [
  // ===== 充电器 (Wall Chargers) =====
  { id:'AU-01', name:'USB Wall Charger AU-01', price:80, brand:'OTU', model:'AU-01', category:'充电器',
    description:'双口USB充电器，2.4A快充，PC+ABS防火材质。',
    specs:[{k:'USB 1',v:'2.4A'},{k:'USB 2',v:'2.4A'},{k:'Input',v:'AC 100-240V,50/60HZ 0.5A'},{k:'Material',v:'PC+ABS'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'},{k:'G.W',v:'14 KG'},{k:'Size',v:'62.2*40.7*37.5 CM'}],
    isHot:true, sort:100 },
  { id:'AU-02', name:'USB Wall Charger AU-02', price:110, brand:'OTU', model:'AU-02', category:'充电器',
    description:'20W快充充电器，支持多电压输出，PC+ABS防火材质。',
    specs:[{k:'Output',v:'DC 5V=4A 9V=2.2A 12V=1.3A 20W'},{k:'Input',v:'AC 100-240V,50/60HZ 0.5A'},{k:'Material',v:'PC+ABS'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'},{k:'G.W',v:'14.8 KG'}],
    isHot:true, sort:95 },
  { id:'AU-03', name:'USB Wall Charger AU-03', price:100, brand:'OTU', model:'AU-03', category:'充电器',
    description:'18W快充充电器，5V-3A输出，PC+ABS防火材质。',
    specs:[{k:'Output',v:'5V-3A(MAX)18W'},{k:'Input',v:'AC 100-240V,50/60HZ 0.5A'},{k:'Material',v:'PC+ABS'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'}],
    isHot:false, sort:80 },
  { id:'AU-04', name:'USB+Type-C Wall Charger AU-04', price:120, brand:'OTU', model:'AU-04', category:'充电器',
    description:'双口USB+Type-C充电器，USB 18W + Type-C 20W，PC+ABS防火材质。',
    specs:[{k:'USB Output',v:'5V-3A(MAX)18W'},{k:'Type-C Output',v:'DC 5V=4A 9V=2.2A 12V=1.3A 20W'},{k:'Input',v:'AC 100-240V,50/60HZ 0.5A'},{k:'Color',v:'White'}],
    isHot:true, sort:90 },

  // ===== 多口充电器 (Multi-port Chargers) =====
  { id:'MT-O1', name:'Multi Charger Cable MT-O1', price:80, brand:'OTU', model:'MT-O1', category:'充电器',
    description:'一拖三充电线，Micro/iPhone/Type-C三接口，5V/2.4A，1000mm。',
    specs:[{k:'Output',v:'5V/2.4A'},{k:'Length',v:'1000MM'},{k:'Material',v:'PC+ABS'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'}],
    isHot:true, sort:85 },
  { id:'MT-O2', name:'Multi Charger Cable MT-O2', price:140, brand:'OTU', model:'MT-O2', category:'充电器',
    description:'一拖三快充线，18W，Micro/iPhone/Type-C，1000mm。',
    specs:[{k:'Output',v:'5V-3A(MAX)18W'},{k:'Length',v:'1000MM'},{k:'Material',v:'PC+ABS'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'}],
    isHot:false, sort:70 },
  { id:'MT-O3', name:'Multi Charger Cable MT-O3', price:160, brand:'OTU', model:'MT-O3', category:'充电器',
    description:'一拖二快充线，Type-C+iPhone，20W，1000mm。',
    specs:[{k:'Output',v:'DC 5V=4A 9V=2.2A 12V=1.3A 20W'},{k:'Length',v:'1000MM'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'}],
    isHot:false, sort:65 },
  { id:'MT-O4', name:'Multi Charger Cable MT-O4', price:120, brand:'OTU', model:'MT-O4', category:'充电器',
    description:'一拖三充电线，18W快充，1000mm。',
    specs:[{k:'Output',v:'5V-3A(MAX)18W'},{k:'Length',v:'1000MM'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'}],
    isHot:false, sort:60 },
  { id:'MT-O5', name:'Multi Charger Cable MT-O5', price:180, brand:'OTU', model:'MT-O5', category:'充电器',
    description:'Type-C快充线，支持PPS协议，最高25W，1000mm。',
    specs:[{k:'Output',v:'5V-3A 9V-2.77A 12V-2.08A PPS:3.3-5.9V-3A'},{k:'Length',v:'1000MM'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:55 },
  { id:'MT-O6', name:'Multi Charger Cable MT-O6', price:190, brand:'OTU', model:'MT-O6', category:'充电器',
    description:'Type-C+iPhone快充线，最高30W，1000mm。',
    specs:[{k:'Output',v:'5V-3A 9V-3A 12V-2.5A'},{k:'Length',v:'1000MM'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'200 PCS'}],
    isHot:false, sort:50 },

  // ===== 车充 (Car Chargers) =====
  { id:'C03', name:'Car Charger C03', price:80, brand:'OTU', model:'C03', category:'车充',
    description:'双USB车充，2.4A，金属材质，DC 12V-24V输入。',
    specs:[{k:'USB 1',v:'2.4A'},{k:'USB 2',v:'2.4A'},{k:'Input',v:'DC 12V-24V'},{k:'Material',v:'Metal'},{k:'Color',v:'Gray'},{k:'Box',v:'50 PCS'}],
    isHot:true, sort:90 },
  { id:'C05', name:'Car Charger C05', price:70, brand:'OTU', model:'C05', category:'车充',
    description:'双USB车充，金属材质，多色可选。',
    specs:[{k:'USB 1',v:'2.4A'},{k:'USB 2',v:'2.4A'},{k:'Input',v:'DC 12V-24V'},{k:'Material',v:'Metal'},{k:'Color',v:'Red/Gray/Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:80 },
  { id:'C06', name:'Car Charger C06 120W', price:190, brand:'OTU', model:'C06', category:'车充',
    description:'120W大功率车充，USB+Type-C双口，支持全协议快充。',
    specs:[{k:'USB Output',v:'5V/3.1A 9V/3A 12V/3A 15V/3A 20V/5A'},{k:'Type-C Output',v:'5V=3A 9V=2.22A 12V=1.66A 120W'},{k:'Input',v:'DC 12V-24V'},{k:'Material',v:'Metal'},{k:'Color',v:'Gray/Golden'}],
    isHot:true, sort:95 },
  { id:'CT-01', name:'Car Charger CT-01', price:150, brand:'OTU', model:'CT-01', category:'车充',
    description:'USB+Type-C车充，USB 22.5W + Type-C 30W。',
    specs:[{k:'USB',v:'22.5W'},{k:'Type-C',v:'30W'},{k:'Input',v:'DC 12V-24V'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:75 },
  { id:'CM-01', name:'Car Charger CM-01', price:150, brand:'OTU', model:'CM-01', category:'车充',
    description:'双USB车充，金属质感，5V/3.1A + 5V/1A。',
    specs:[{k:'USB 1',v:'5V/3.1A'},{k:'USB 2',v:'5V/1A'},{k:'Input',v:'DC 12V-24V'},{k:'Color',v:'Black/Silver'},{k:'Box',v:'40 PCS'}],
    isHot:false, sort:70 },
  { id:'CM-02', name:'Car Charger CM-02', price:200, brand:'OTU', model:'CM-02', category:'车充',
    description:'三口车充，双USB+Type-C，5V/3.1A。',
    specs:[{k:'USB',v:'U1/5V/3.1A U2/5V/1A'},{k:'Type-C',v:'5V/3.1A'},{k:'Input',v:'DC 12V-24V'},{k:'Color',v:'Black'},{k:'Box',v:'40 PCS'}],
    isHot:false, sort:65 },

  // ===== 蓝牙接收器 =====
  { id:'CS-01', name:'Bluetooth Receiver CS-01', price:80, brand:'OTU', model:'CS-01', category:'接收器',
    description:'3.5mm蓝牙接收器，TPE材质，让有线音响变蓝牙。',
    specs:[{k:'Interface',v:'3.5mm'},{k:'Material',v:'TPE'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'},{k:'Carton',v:'300 PCS'}],
    isHot:false, sort:70 },

  // ===== 数据线 (Data Cables) =====
  { id:'DL-02', name:'Data Cable DL-02', price:70, brand:'OTU', model:'DL-02', category:'数据线',
    description:'金属+硅胶数据线，5A大电流，Micro/iPhone/Type-C，1000mm。',
    specs:[{k:'Current',v:'5A'},{k:'Length',v:'1000MM'},{k:'Material',v:'Metal+Silicone'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:true, sort:90 },
  { id:'DL-05', name:'Data Cable DL-05', price:80, brand:'OTU', model:'DL-05', category:'数据线',
    description:'3A数据线，2000mm加长，TPE材质，Micro/iPhone/Type-C。',
    specs:[{k:'Current',v:'3A'},{k:'Length',v:'2000MM'},{k:'Material',v:'TPE'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:true, sort:85 },
  { id:'DL-06', name:'3in1 Data Cable DL-06', price:80, brand:'OTU', model:'DL-06', category:'数据线',
    description:'三合一线，Micro+Type-C+iPhone，3A，1200mm。',
    specs:[{k:'Current',v:'3A'},{k:'Length',v:'1200MM'},{k:'Material',v:'TPE'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:true, sort:88 },
  { id:'DL-07', name:'Data Cable DL-07 CtoL', price:80, brand:'OTU', model:'DL-07', category:'数据线',
    description:'Type-C to iPhone数据线，20W快充，1000mm。',
    specs:[{k:'Current',v:'20W'},{k:'Length',v:'1000MM'},{k:'Material',v:'TPE'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:75 },
  { id:'DL-08', name:'Data Cable DL-08 CtoC', price:70, brand:'OTU', model:'DL-08', category:'数据线',
    description:'Type-C to Type-C数据线，60W快充，1000mm。',
    specs:[{k:'Current',v:'60W'},{k:'Length',v:'1000MM'},{k:'Material',v:'TPE'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:72 },
  { id:'DL-302', name:'Data Cable DL-302', price:90, brand:'OTU', model:'DL-302', category:'数据线',
    description:'3.6A金属编织三合一线，1200mm，黑色。',
    specs:[{k:'Current',v:'3.6A'},{k:'Length',v:'1200MM'},{k:'Material',v:'Metal+Braided'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:78 },
  { id:'DL-11', name:'Data Cable DL-11', price:70, brand:'OTU', model:'DL-11', category:'数据线',
    description:'5A硅胶数据线，1000mm，Micro/iPhone/Type-C。',
    specs:[{k:'Current',v:'5A'},{k:'Length',v:'1000MM'},{k:'Material',v:'Silica Gel'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:68 },
  { id:'DL-12', name:'Data Cable DL-12', price:70, brand:'OTU', model:'DL-12', category:'数据线',
    description:'5A金属编织数据线，1000mm，黑色。',
    specs:[{k:'Current',v:'5A'},{k:'Length',v:'1000MM'},{k:'Material',v:'Metal+Braided'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:65 },
  { id:'DL-19', name:'Data Cable DL-19', price:70, brand:'OTU', model:'DL-19', category:'数据线',
    description:'5A硅胶数据线，1000mm。',
    specs:[{k:'Current',v:'5A'},{k:'Length',v:'1000MM'},{k:'Material',v:'Silicone'},{k:'Color',v:'White'},{k:'Box',v:'45 PCS'}],
    isHot:false, sort:62 },
  { id:'DL-20', name:'Data Cable DL-20', price:50, brand:'OTU', model:'DL-20', category:'数据线',
    description:'5A编织数据线，1000mm，黑色。',
    specs:[{k:'Current',v:'5A'},{k:'Length',v:'1000MM'},{k:'Material',v:'TPE+Braided'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:60 },
  { id:'DL-202', name:'Data Cable DL-202', price:70, brand:'OTU', model:'DL-202', category:'数据线',
    description:'5A编织数据线，2000mm加长，黑色。',
    specs:[{k:'Current',v:'5A'},{k:'Length',v:'2000MM'},{k:'Material',v:'TPE+Braided'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:58 },
  { id:'DL-21', name:'Data Cable DL-21 Series', price:40, brand:'OTU', model:'DL-21', category:'数据线',
    description:'入门数据线系列，TPE材质，1000mm。5种接口可选。',
    specs:[{k:'Variants',v:'DL21-I/C/V/IC/CC'},{k:'Current',v:'2.4A~60W'},{k:'Length',v:'1000MM'},{k:'Material',v:'TPE'},{k:'Color',v:'White'}],
    isHot:false, sort:55 },
  { id:'DL-22', name:'Data Cable DL-22', price:50, brand:'OTU', model:'DL-22', category:'数据线',
    description:'3A编织数据线，iPhone接口，1000mm，黑色。',
    specs:[{k:'Current',v:'3A'},{k:'Length',v:'1000MM'},{k:'Material',v:'TPE+Braided'},{k:'Color',v:'Black'},{k:'Box',v:'30 PCS'}],
    isHot:false, sort:50 },

  // ===== 有线耳机 (Wired Earphones) =====
  { id:'HJ-01', name:'Wired Earphone HJ-01', price:55, brand:'OTU', model:'HJ-01', category:'有线耳机',
    description:'3.5mm有线耳机，TPE+ABS材质，1200mm线长。',
    specs:[{k:'Plug',v:'3.5MM'},{k:'Length',v:'1200MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:true, sort:88 },
  { id:'HJ-04', name:'Wired Earphone HJ-04', price:70, brand:'OTU', model:'HJ-04', category:'有线耳机',
    description:'3.5mm金属耳机，金属+TPE，1200mm。',
    specs:[{k:'Plug',v:'3.5MM'},{k:'Length',v:'1200MM'},{k:'Material',v:'Metal+TPE'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:75 },
  { id:'HJ-06', name:'Wired Earphone HJ-06', price:80, brand:'OTU', model:'HJ-06', category:'有线耳机',
    description:'3.5mm金属耳机，深蓝色，1200mm。',
    specs:[{k:'Plug',v:'3.5MM'},{k:'Length',v:'1200MM'},{k:'Material',v:'Metal+TPE'},{k:'Color',v:'Dark Blue'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:72 },
  { id:'HJ-08', name:'Earphone HJ-08 with Mic', price:70, brand:'OTU', model:'HJ-08', category:'有线耳机',
    description:'带线控耳机，支持音量调节/播放暂停，3.5mm/Lighting/Type-C可选。',
    specs:[{k:'Function',v:'音量/暂停/Siri/通话'},{k:'Length',v:'1000MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'White'},{k:'Box',v:'45 PCS'}],
    isHot:true, sort:85 },
  { id:'HJ-10', name:'Wired Earphone HJ-10', price:40, brand:'OTU', model:'HJ-10', category:'有线耳机',
    description:'入门款3.5mm耳机，TPE+ABS，1200mm。',
    specs:[{k:'Plug',v:'3.5MM'},{k:'Length',v:'1200MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'White'},{k:'Box',v:'30 PCS'}],
    isHot:false, sort:60 },
  { id:'HJ-11', name:'Wired Earphone HJ-11', price:40, brand:'OTU', model:'HJ-11', category:'有线耳机',
    description:'入门款3.5mm耳机，1200mm。',
    specs:[{k:'Plug',v:'3.5MM'},{k:'Length',v:'1200MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'White'},{k:'Box',v:'30 PCS'}],
    isHot:false, sort:58 },
  { id:'HJ-13', name:'Type-C Earphone HJ-13', price:100, brand:'OTU', model:'HJ-13', category:'有线耳机',
    description:'Type-C接口耳机，内置DAC芯片，1200mm。',
    specs:[{k:'Plug',v:'Type-C(内置IC)'},{k:'Length',v:'1200MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'Black/White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:70 },
  { id:'HJ-14', name:'Type-C Earphone HJ-14', price:100, brand:'OTU', model:'HJ-14', category:'有线耳机',
    description:'Type-C接口耳机，内置DAC，1200mm。',
    specs:[{k:'Plug',v:'Type-C(内置IC)'},{k:'Length',v:'1200MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'Black/White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:68 },
  { id:'HJ-15', name:'Type-C Earphone HJ-15', price:100, brand:'OTU', model:'HJ-15', category:'有线耳机',
    description:'Type-C接口耳机，内置DAC，1200mm。',
    specs:[{k:'Plug',v:'Type-C(内置IC)'},{k:'Length',v:'1200MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'Black/White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:65 },
  { id:'HJ-20', name:'Gaming Headphone HJ-20', price:480, brand:'OTU', model:'HJ-20', category:'有线耳机',
    description:'游戏头戴耳机，50mm驱动单元，20mW输出，2100mm线长。',
    specs:[{k:'Speaker',v:'Φ50mm /20Hz-20KHz'},{k:'Microphone',v:'Φ6*5 /-42±3dB'},{k:'Line Length',v:'2100±50mm'},{k:'Output',v:'20mW(1KHz 0dB)'},{k:'Color',v:'Black'},{k:'Box',v:'20 PCS'}],
    isHot:true, sort:92 },

  // ===== 音频线/转接头 =====
  { id:'X02', name:'Aux Cable X02', price:50, brand:'OTU', model:'X02', category:'数据线',
    description:'金属编织AUX音频线，3.5mm/Lighting/Type-C可选，1800mm。',
    specs:[{k:'Length',v:'1800MM'},{k:'Material',v:'Metal+Braided'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:60 },
  { id:'X03', name:'AUX Audio Cable X03', price:40, brand:'OTU', model:'X03', category:'数据线',
    description:'3.5mm to 3.5mm AUX音频线，1000mm。',
    specs:[{k:'Plug',v:'3.5mm to 3.5mm'},{k:'Length',v:'1000MM'},{k:'Material',v:'TPE'},{k:'Color',v:'White'},{k:'Box',v:'30 PCS'}],
    isHot:false, sort:50 },
  { id:'X04', name:'OTG Adapter X04', price:90, brand:'OTU', model:'X04', category:'数据线',
    description:'OTG转接头，iPhone/Type-C可选，10mm。',
    specs:[{k:'Length',v:'10MM'},{k:'Material',v:'TPE+ABS'},{k:'Color',v:'White'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:55 },

  // ===== 蓝牙耳机 (TWS Earbuds) =====
  { id:'AI-02', name:'TWS Airpods Pro AI-02', price:300, brand:'OTU', model:'AI-02', category:'蓝牙耳机',
    description:'蓝牙5.1 TWS耳机，AC6973芯片，5小时续航。',
    specs:[{k:'Solutions',v:'AC6973/Bluetooth5.1'},{k:'Battery',v:'300MAH/30MAH'},{k:'Music/Talk',v:'5/3 Hours'},{k:'Charging',v:'1-2 Hours'},{k:'Color',v:'White'},{k:'Box',v:'20/120 PCS'}],
    isHot:true, sort:95 },
  { id:'AI-03', name:'TWS Airpods Pro AI-03', price:300, brand:'OTU', model:'AI-03', category:'蓝牙耳机',
    description:'蓝牙5.1 TWS，AC6973芯片，300mAh充电仓。',
    specs:[{k:'Solutions',v:'AC6973/Bluetooth5.1'},{k:'Battery',v:'300MAH/30MAH'},{k:'Music/Talk',v:'5/3 Hours'},{k:'Color',v:'White'}],
    isHot:false, sort:82 },
  { id:'AI-04', name:'TWS Airpods Pro AI-04', price:300, brand:'OTU', model:'AI-04', category:'蓝牙耳机',
    description:'蓝牙5.1 TWS，LC6973芯片，200mAh充电仓。',
    specs:[{k:'Solutions',v:'LC6973/Bluetooth5.1'},{k:'Battery',v:'200MAH/25MAH'},{k:'Music/Talk',v:'4/3 Hours'},{k:'Color',v:'White'}],
    isHot:false, sort:78 },
  { id:'AI-04P', name:'TWS Airpods Pro AI-04 Pro', price:340, brand:'OTU', model:'AI-04 Pro', category:'蓝牙耳机',
    description:'蓝牙5.1 TWS Pro版，LC6973芯片，300mAh大电池。',
    specs:[{k:'Solutions',v:'LC6973/Bluetooth5.1'},{k:'Battery',v:'300MAH/30MAH'},{k:'Music/Talk',v:'5/4 Hours'},{k:'Color',v:'White'}],
    isHot:true, sort:88 },
  { id:'AI-07', name:'Bluetooth Headphone AI-07', price:300, brand:'OTU', model:'AI-07', category:'蓝牙耳机',
    description:'蓝牙5.0头戴耳机，BK3266芯片，120小时超长待机，7小时续航。',
    specs:[{k:'Solutions',v:'BK3266/5.0'},{k:'Battery',v:'120 Hours Standby'},{k:'Music/Talk',v:'7/7 Hours'},{k:'Color',v:'Dark Blue/Pink/Tarnish'},{k:'Box',v:'28/112 PCS'}],
    isHot:false, sort:75 },
  { id:'AI-09', name:'TWS Airpods Pro AI-09', price:350, brand:'OTU', model:'AI-09', category:'蓝牙耳机',
    description:'蓝牙5.3 TWS，JL6973D4芯片，黑白可选。',
    specs:[{k:'Solutions',v:'JL6973D4/Bluetooth5.3'},{k:'Battery',v:'300MAH/30MAH'},{k:'Music/Talk',v:'4/3 Hours'},{k:'Color',v:'White/Black'},{k:'Box',v:'50/200 PCS'}],
    isHot:true, sort:86 },
  { id:'AI-14', name:'TWS Airpods Pro AI-14', price:270, brand:'OTU', model:'AI-14', category:'蓝牙耳机',
    description:'蓝牙5.1 TWS，LC6983芯片，黑白可选。',
    specs:[{k:'Solutions',v:'LC6983/Bluetooth5.1'},{k:'Battery',v:'230MAH/30MAH'},{k:'Music/Talk',v:'4/3 Hours'},{k:'Color',v:'White/Black'},{k:'Box',v:'50/200 PCS'}],
    isHot:false, sort:72 },
  { id:'AI-16', name:'TWS Airpods Pro AI-16', price:280, brand:'OTU', model:'AI-16', category:'蓝牙耳机',
    description:'蓝牙5.3 TWS，JL6983D2芯片，250mAh。',
    specs:[{k:'Solutions',v:'JL6983D2/Bluetooth5.3'},{k:'Battery',v:'250MAH/25MAH'},{k:'Music/Talk',v:'5/3 Hours'},{k:'Color',v:'White/Black'}],
    isHot:false, sort:70 },
  { id:'AI-17', name:'TWS Airpods Pro AI-17', price:200, brand:'OTU', model:'AI-17', category:'蓝牙耳机',
    description:'蓝牙5.4 TWS，AC6983D芯片，最新蓝牙标准。',
    specs:[{k:'Solutions',v:'AC6983D/Bluetooth5.4'},{k:'Battery',v:'200MAH/30MAH'},{k:'Music/Talk',v:'4 Hours'},{k:'Color',v:'White'},{k:'Box',v:'50/200 PCS'}],
    isHot:true, sort:84 },
  { id:'AI-18', name:'TWS Airpods Pro AI-18', price:200, brand:'OTU', model:'AI-18', category:'蓝牙耳机',
    description:'蓝牙5.4 TWS，AC6983D芯片，180mAh。',
    specs:[{k:'Solutions',v:'AC6983D/Bluetooth5.4'},{k:'Battery',v:'180MAH/30MAH'},{k:'Music/Talk',v:'4 Hours'},{k:'Color',v:'White'},{k:'Box',v:'50/200 PCS'}],
    isHot:false, sort:68 },
  { id:'AI-19', name:'TWS Airpods Pro AI-19', price:200, brand:'OTU', model:'AI-19', category:'蓝牙耳机',
    description:'蓝牙5.4 TWS，AC6983D芯片。',
    specs:[{k:'Solutions',v:'AC6983D/Bluetooth5.4'},{k:'Battery',v:'180MAH/30MAH'},{k:'Music/Talk',v:'4 Hours'},{k:'Color',v:'White'}],
    isHot:false, sort:65 },
  { id:'AI-20', name:'TWS Airpods Pro AI-20', price:200, brand:'OTU', model:'AI-20', category:'蓝牙耳机',
    description:'蓝牙5.4 TWS，AC6983D芯片，200mAh。',
    specs:[{k:'Solutions',v:'AC6983D/Bluetooth5.4'},{k:'Battery',v:'200MAH/30MAH'},{k:'Music/Talk',v:'4 Hours'},{k:'Color',v:'White'}],
    isHot:false, sort:62 },
  { id:'AI-30', name:'Bluetooth Headphone AI-30', price:520, brand:'OTU', model:'AI-30', category:'蓝牙耳机',
    description:'蓝牙5.1头戴耳机，6925芯片，500mAh大电池，15小时续航。',
    specs:[{k:'Solutions',v:'6925/Bluetooth 5.1'},{k:'Battery',v:'3.7V/500 MAH'},{k:'Play Time',v:'15 Hours'},{k:'Color',v:'Gray'},{k:'Box',v:'40 PCS'}],
    isHot:false, sort:74 },

  // ===== 蓝牙音箱 (Bluetooth Speakers) =====
  { id:'BS-01', name:'Bluetooth Speaker BS-01', price:550, brand:'OTU', model:'BS-01', category:'蓝牙音箱',
    description:'蓝牙5.0音箱，双5W全频喇叭+双低音振膜，1800mAh。',
    specs:[{k:'Solutions',v:'V5.0+EDR'},{k:'Speaker',v:'5W全频*2+低音振膜*2'},{k:'Battery',v:'1800 MAH'},{k:'Music/Talk',v:'6/6 Hours'},{k:'Color',v:'Black'},{k:'Carton',v:'20 PCS'}],
    isHot:true, sort:90 },
  { id:'BS-06', name:'Bluetooth Speaker BS-06', price:900, brand:'OTU', model:'BS-06', category:'蓝牙音箱',
    description:'蓝牙5.3大功率音箱，双78mm 15W全频+双低音振膜，4500mAh。',
    specs:[{k:'Solutions',v:'V5.3+EDR+BLE+BR'},{k:'Speaker',v:'2*78mm 4Ω15W+2*低音振膜'},{k:'Battery',v:'4500mAh'},{k:'Music',v:'8-10 Hours'},{k:'Color',v:'Black'},{k:'Box',v:'10 PCS'}],
    isHot:true, sort:85 },
  { id:'BS-07', name:'Bluetooth Speaker BS-07', price:280, brand:'OTU', model:'BS-07', category:'蓝牙音箱',
    description:'蓝牙5.3便携音箱，6965芯片，多色可选，1200mAh。',
    specs:[{k:'Solutions',v:'JL 6965 V5.3'},{k:'Speaker',v:'5W全频+低音振膜'},{k:'Battery',v:'1200 MAH'},{k:'Color',v:'Black/Green/Purple/Blue'},{k:'Box',v:'40 PCS'}],
    isHot:true, sort:88 },
  { id:'BS-08', name:'LED Outdoor Speaker BS-08', price:450, brand:'OTU', model:'BS-08', category:'蓝牙音箱',
    description:'蓝牙5.3户外LED音箱，6966芯片，1800mAh，6小时续航。',
    specs:[{k:'Solutions',v:'JL 6966 V5.3'},{k:'Speaker',v:'5W全频+低音振膜'},{k:'Battery',v:'1800 MAH'},{k:'Music',v:'6/4 Hours'},{k:'Color',v:'Black/Blue'},{k:'Box',v:'20 PCS'}],
    isHot:false, sort:78 },

  // ===== 车载支架 (Car Mounts) =====
  { id:'ZH-01', name:'Car Bracket ZH-01', price:110, brand:'OTU', model:'ZH-01', category:'车载支架',
    description:'一键启动车载支架，PC+ABS材质。',
    specs:[{k:'Function',v:'A Key to Start'},{k:'Material',v:'PC+ABS'},{k:'Color',v:'Black'},{k:'Box',v:'24 PCS'}],
    isHot:false, sort:72 },
  { id:'ZH-04', name:'Magnetic Car Bracket ZH-04', price:70, brand:'OTU', model:'ZH-04', category:'车载支架',
    description:'磁吸车载支架，金属材质。',
    specs:[{k:'Function',v:'Magnet'},{k:'Material',v:'Metal'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:true, sort:80 },
  { id:'ZH-05', name:'Magnetic Car Bracket ZH-05', price:100, brand:'OTU', model:'ZH-05', category:'车载支架',
    description:'磁吸车载支架，ABS+硅胶。',
    specs:[{k:'Function',v:'Magnet'},{k:'Material',v:'ABS+Silicone'},{k:'Color',v:'Black'},{k:'Box',v:'26 PCS'}],
    isHot:false, sort:75 },
  { id:'ZH-08', name:'Auto Car Bracket ZH-08', price:100, brand:'OTU', model:'ZH-08', category:'车载支架',
    description:'重力感应车载支架，PC+ABS，自动夹紧。',
    specs:[{k:'Function',v:'Accelerometer'},{k:'Material',v:'PC+ABS'},{k:'Color',v:'Black'},{k:'Box',v:'20 PCS'}],
    isHot:true, sort:82 },
  { id:'ZH-10', name:'Magnetic Car Bracket ZH-10', price:110, brand:'OTU', model:'ZH-10', category:'车载支架',
    description:'金属磁吸支架。',
    specs:[{k:'Function',v:'Magnet'},{k:'Material',v:'Metal'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:68 },
  { id:'ZH-101', name:'Phone Holder ZH-101', price:80, brand:'OTU', model:'ZH-101', category:'车载支架',
    description:'伸缩折叠手机支架，PC+ABS，黑白可选。',
    specs:[{k:'Function',v:'Telescopic Folding'},{k:'Material',v:'PC+ABS'},{k:'Color',v:'Black/White'},{k:'Box',v:'40 PCS'}],
    isHot:false, sort:65 },
  { id:'ZH-201', name:'Car Bracket ZH-201', price:100, brand:'OTU', model:'ZH-201', category:'车载支架',
    description:'旋转一键锁定车载支架，ABS+EVA+硅胶。',
    specs:[{k:'Function',v:'Rotate One Button Lock'},{k:'Material',v:'ABS+EVA+硅胶'},{k:'Color',v:'Black'},{k:'Box',v:'22 PCS'}],
    isHot:false, sort:62 },
  { id:'ZH-202', name:'Car Bracket ZH-202', price:100, brand:'OTU', model:'ZH-202', category:'车载支架',
    description:'360°伸缩折叠车载支架，ABS+TPU+硅胶+皮质。',
    specs:[{k:'Function',v:'360° Telescopic Folding'},{k:'Material',v:'ABS+TPU+硅胶+皮质'},{k:'Color',v:'Black'},{k:'Box',v:'18 PCS'}],
    isHot:false, sort:60 },

  // ===== 移动电源 (Power Banks) =====
  { id:'PB-101', name:'Power Bank PB-101 10000mAh', price:260, brand:'OTU', model:'PB-101', category:'移动电源',
    description:'10000mAh移动电源，5V/2.4A，ABS材质，黑白可选。',
    specs:[{k:'Battery',v:'10000MAH/6300MAH'},{k:'Output',v:'DC 5V/2.4A'},{k:'Input',v:'DC 5V/2A(MAX)'},{k:'Material',v:'ABS'},{k:'Color',v:'White/Black'},{k:'Box',v:'20/40 PCS'}],
    isHot:true, sort:90 },
  { id:'PB-102', name:'Power Bank PB-102 10000mAh', price:350, brand:'OTU', model:'PB-102', category:'移动电源',
    description:'10000mAh快充移动电源，USB 22.5W + Type-C 20W。',
    specs:[{k:'Battery',v:'10000MAH/6200MAH'},{k:'Output',v:'USB/22.5W C/20W'},{k:'Input',v:'18W(MAX)'},{k:'Color',v:'White/Black'},{k:'Box',v:'20/40 PCS'}],
    isHot:true, sort:88 },
  { id:'PB-103', name:'Power Bank PB-103 10000mAh', price:300, brand:'OTU', model:'PB-103', category:'移动电源',
    description:'10000mAh移动电源，5V/2.4A输出。',
    specs:[{k:'Battery',v:'10000MAH/6300MAH'},{k:'Output',v:'DC 5V/2.4A'},{k:'Input',v:'DC 5V/2A(MAX)'},{k:'Color',v:'White'},{k:'Box',v:'20/40 PCS'}],
    isHot:false, sort:75 },
  { id:'PB-201', name:'Power Bank PB-201 20000mAh', price:0, brand:'OTU', model:'PB-201', category:'移动电源',
    description:'20000mAh大容量移动电源，5V/2.4A。价格待询。',
    specs:[{k:'Battery',v:'20000MAH/12500MAH'},{k:'Output',v:'DC 5V/2.4A'},{k:'Input',v:'DC 5V/2A(MAX)'},{k:'Color',v:'White/Black'},{k:'Box',v:'20/40 PCS'}],
    isHot:false, sort:72 },
  { id:'PB-202', name:'Power Bank PB-202 20000mAh', price:450, brand:'OTU', model:'PB-202', category:'移动电源',
    description:'20000mAh快充移动电源，USB 22.5W + Type-C 20W。',
    specs:[{k:'Battery',v:'20000MAH/12500MAH'},{k:'Output',v:'USB/22.5W C/20W'},{k:'Input',v:'18W(MAX)'},{k:'Color',v:'White'},{k:'Box',v:'20/40 PCS'}],
    isHot:true, sort:86 },
  { id:'PB-203', name:'Power Bank PB-203 20000mAh', price:450, brand:'OTU', model:'PB-203', category:'移动电源',
    description:'20000mAh移动电源，5V/2.1A。',
    specs:[{k:'Battery',v:'20000MAH/12600MAH'},{k:'Output',v:'DC 5V/2.1A'},{k:'Input',v:'DC 5V/2.1A(MAX)'},{k:'Color',v:'White'},{k:'Box',v:'20/40 PCS'}],
    isHot:false, sort:70 },

  // ===== 转接头 (Adapters) =====
  { id:'Z01', name:'OTG Adapter Z01', price:140, brand:'OTU', model:'Z01', category:'数据线',
    description:'USB/Type-C OTG转接头，150mm，ABS材质。',
    specs:[{k:'Length',v:'150MM'},{k:'Material',v:'ABS'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:50 },
  { id:'Z02', name:'OTG Adapter Z02', price:60, brand:'OTU', model:'Z02', category:'数据线',
    description:'Type-C OTG转接头，35mm，金属材质，灰色。',
    specs:[{k:'Length',v:'35MM'},{k:'Material',v:'Metal'},{k:'Color',v:'Gray'}],
    isHot:false, sort:48 },

  // ===== 排插 (Power Strips) =====
  { id:'BK-02', name:'Power Strip BK-02', price:300, brand:'OTU', model:'BK-02', category:'排插',
    description:'4插座+6USB排插，3000W/10A，2000mm线长，阻燃PC。US/EU/UK可选。',
    specs:[{k:'Rated',v:'3000W/10A/100V-250V'},{k:'Output',v:'Sockets*4/USB*6'},{k:'USB Output',v:'DC 5V/4.2A'},{k:'Length',v:'2000MM'},{k:'Material',v:'阻燃PC'},{k:'Color',v:'Black/White'},{k:'Carton',v:'40 PCS'}],
    isHot:true, sort:85 },
  { id:'BK-03', name:'Power Strip BK-03', price:370, brand:'OTU', model:'BK-03', category:'排插',
    description:'6插座+6USB排插，3000W/10A，2000mm，阻燃PC。',
    specs:[{k:'Rated',v:'3000W/10A/100V-250V'},{k:'Output',v:'Sockets*6/USB*6'},{k:'USB Output',v:'DC 5V/4.2A'},{k:'Length',v:'2000MM'},{k:'Material',v:'阻燃PC'},{k:'Carton',v:'36 PCS'}],
    isHot:false, sort:80 },

  // ===== 键鼠 (Keyboards & Mice) =====
  { id:'JP-01', name:'USB Keyboard JP-01', price:150, brand:'OTU', model:'JP-01', category:'键鼠',
    description:'USB有线键盘，ABS材质，1350mm线长。',
    specs:[{k:'Length',v:'1350mm'},{k:'Material',v:'ABS'},{k:'Color',v:'Black'},{k:'Box',v:'40 PCS'}],
    isHot:false, sort:70 },
  { id:'JP-02', name:'USB Light Keyboard JP-02', price:230, brand:'OTU', model:'JP-02', category:'键鼠',
    description:'USB有线发光键盘，ABS，1350mm。',
    specs:[{k:'Length',v:'1350mm'},{k:'Material',v:'ABS'},{k:'Color',v:'Black'},{k:'Box',v:'30 PCS'}],
    isHot:true, sort:78 },
  { id:'JP-11', name:'Wireless Keyboard Mouse Kit JP-11', price:300, brand:'OTU', model:'JP-11', category:'键鼠',
    description:'无线键鼠套装，2.4G连接。',
    specs:[{k:'Connection',v:'Wireless'},{k:'Material',v:'ABS'},{k:'Color',v:'Black'},{k:'Box',v:'30 PCS'}],
    isHot:true, sort:82 },
  { id:'S01', name:'USB Mouse S01', price:70, brand:'OTU', model:'S01', category:'键鼠',
    description:'USB有线鼠标，ABS，1200mm。',
    specs:[{k:'Length',v:'1200MM'},{k:'Material',v:'ABS'},{k:'Color',v:'Black'}],
    isHot:false, sort:60 },
  { id:'S02', name:'USB Gaming Mouse S02', price:150, brand:'OTU', model:'S02', category:'键鼠',
    description:'USB有线游戏鼠标，1800mm。',
    specs:[{k:'Length',v:'1800MM'},{k:'Material',v:'ABS'},{k:'Color',v:'Black'},{k:'Box',v:'21 PCS'}],
    isHot:true, sort:75 },
  { id:'S11', name:'Wireless Mouse S11', price:110, brand:'OTU', model:'S11', category:'键鼠',
    description:'2.4G无线鼠标，ABS材质。',
    specs:[{k:'Connection',v:'Wireless'},{k:'Material',v:'ABS'},{k:'Color',v:'Black'}],
    isHot:true, sort:80 },
  { id:'MS-01', name:'Silicone Mouse Pad MS-01', price:60, brand:'OTU', model:'MS-01', category:'键鼠',
    description:'硅胶鼠标垫，210*260*30mm，环保橡胶+布面。',
    specs:[{k:'Size',v:'210*260*30mm'},{k:'Material',v:'环保橡胶+布面'},{k:'Color',v:'Black'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:55 },

  // ===== 存储 (Storage) =====
  { id:'E03', name:'USB Flash Drive E03', price:100, brand:'OTU', model:'E03', category:'存储',
    description:'金属U盘，SMI+MLC芯片，USB2.0，2GB-128GB可选。',
    specs:[{k:'Chip',v:'SMI+MLC'},{k:'Speed',v:'USB2.0 10M/30M'},{k:'Material',v:'Metal'},{k:'Capacity',v:'2GB-128GB'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:65 },
  { id:'SD', name:'SD Memory Card', price:100, brand:'OTU', model:'SD Card', category:'存储',
    description:'SD存储卡，2GB-128GB可选。价格以当日订货为准。',
    specs:[{k:'Capacity',v:'2GB-128GB'},{k:'Speed',v:'Up to 100MB/S'},{k:'Box',v:'50 PCS'}],
    isHot:false, sort:60 }
];

// 更新分类
const categories = ['充电器', '车充', '数据线', '蓝牙耳机', '有线耳机', '蓝牙音箱', '移动电源', '车载支架', '排插', '键鼠', '存储', '接收器'];
